services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "9000:5432"  # Host port 9000 → Container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
